package com.example.jpastart.controller;

import com.example.jpastart.model.Student;
import com.example.jpastart.repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@RestController
public class StudentRestController {

    @Autowired
    StudentRepository sr;

    // Returns JSON with the Students
    @GetMapping("/students")
    public List<Student> students() {
        List<Student> lst = sr.findAll();
        return lst;
    }

    @GetMapping("/addstudent")
    public List<Student> addStudent() {
        Student std1 = new Student();
        List<Student> lst = sr.findAll();
        std1.setName("Autogenerated size = " +  lst.size());
        std1.setBorn(LocalDate.now());
        std1.setBornTime(LocalTime.now());
        sr.save(std1);
        return lst;
    }

}
